=== NordIQuEst/tergite-frontend/src/schemas/2024-07/device.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/tergite/tergite-dashboard/tree/main/src/schemas/2024-07/device.json",
  "title": "Device",
  "description": "A quantum computing backend specification",
  "type": "object",
  "properties": {
    "id": {
      "description": "The unique identifier of the record in the database",
      "type": "string"
    },
    "name": {
      "description": "The unique name of the quantum computer",
      "type": "string"
    },
    "version": {
      "description": "The revision of this quantum computer",
      "type": "string"
    },
    "number_of_qubits": {
      "description": "The number of qubits in the quantum computer",
      "type": "integer",
      "minimum": 0
    },
    "last_online": {
      "description": "The last time this device was seen online",
      "anyOf": [
        {
          "type": "string",
          "format": "date-time"
        },
        { "type": "null" }
      ]
    },
    "is_online": {
      "description": "Whether the quantum computer is online or not",
      "type": "boolean"
    },
    "basis_gates": {
      "description": "The unique name of the quantum computer",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "coupling_map": {
      "description": "The uni-directional mapping showing how each qubit is connected",
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "integer",
          "minimum": 0
        },
        "minItems": 2,
        "maxItems": 2
      }
    },
    "coordinates": {
      "description": "The x,y coordinates of the qubits on the chip",
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "integer",
          "minimum": 0
        },
        "minItems": 2,
        "maxItems": 2
      }
    },
    "is_simulator": {
      "description": "Whether this is a simulator",
      "type": "boolean"
    },
    "created_at": {
      "description": "The ISO 8601 timestamp when this record was created in the database",
      "anyOf": [
        {
          "type": "string",
          "format": "date-time"
        },
        { "type": "null" }
      ]
    },
    "updated_at": {
      "description": "The ISO 8601 timestamp when this record was last updated in the database",
      "anyOf": [
        {
          "type": "string",
          "format": "date-time"
        },
        { "type": "null" }
      ]
    }
  },
  "required": [
    "id",
    "name",
    "version",
    "number_of_qubits",
    "is_online",
    "basis_gates",
    "is_simulator",
    "coupling_map"
  ]
}

=== NordIQuEst/tergite-frontend/apps/tergite-dashboard/cypress/fixtures/device-list.json
[
  {
    "id": "loke",
    "name": "Loke",
    "version": "2024.04.1",
    "number_of_qubits": 8,
    "is_online": false,
    "last_online": "2024-05-23T09:12:00.733Z",
    "basis_gates": ["u", "h", "x"],
    "is_simulator": false,
    "coupling_map": [
      [0, 1],
      [1, 2],
      [0, 3],
      [1, 4],
      [3, 4],
      [2, 5],
      [4, 5],
      [3, 6],
      [5, 7],
      [6, 7]
    ],
    "coordinates": [
      [1, 1],
      [2, 1],
      [3, 2],
      [1, 2],
      [2, 2],
      [3, 2],
      [1, 3],
      [3, 3]
    ]
  },
  {
    "id": "thor",
    "name": "Thor",
    "version": "2023.06.0",
    "number_of_qubits": 5,
    "is_online": true,
    "last_online": null,
    "basis_gates": ["u", "h", "x"],
    "is_simulator": true,
    "coupling_map": [
      [0, 1],
      [0, 2],
      [2, 3],
      [1, 4],
      [3, 4]
    ],
    "coordinates": [
      [1, 1],
      [3, 1],
      [1, 2],
      [2, 2],
      [3, 2]
    ]
  },
  {
    "id": "pingu",
    "name": "Pingu",
    "version": "2024.05.1",
    "number_of_qubits": 20,
    "is_online": false,
    "last_online": "2024-05-24T09:12:00.733Z",
    "basis_gates": ["u", "h", "x"],
    "is_simulator": false,
    "coupling_map": [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
      [0, 5],
      [1, 6],
      [5, 6],
      [2, 7],
      [6, 7],
      [3, 8],
      [7, 8],
      [4, 9],
      [8, 9],
      [5, 10],
      [10, 11],
      [6, 11],
      [11, 12],
      [7, 12],
      [12, 13],
      [8, 13],
      [13, 14],
      [10, 15],
      [15, 16],
      [11, 16],
      [16, 17],
      [12, 17],
      [17, 18],
      [13, 18],
      [18, 19]
    ],
    "coordinates": [
      [1, 1],
      [2, 1],
      [3, 1],
      [4, 1],
      [5, 1],
      [1, 2],
      [2, 2],
      [3, 2],
      [4, 2],
      [5, 2],
      [1, 3],
      [2, 3],
      [3, 3],
      [4, 3],
      [5, 3],
      [1, 4],
      [2, 4],
      [3, 4],
      [4, 4],
      [5, 4]
    ]
  },
  {
    "id": "pegu",
    "name": "Pegu",
    "version": "2024.05.1",
    "number_of_qubits": 20,
    "is_online": false,
    "last_online": "2024-05-24T09:12:00.733Z",
    "basis_gates": ["u", "h", "x"],
    "is_simulator": false,
    "coupling_map": [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
      [0, 5],
      [1, 6],
      [5, 6],
      [2, 7],
      [6, 7],
      [3, 8],
      [7, 8],
      [4, 9],
      [8, 9],
      [5, 10],
      [10, 11],
      [6, 11],
      [11, 12],
      [7, 12],
      [12, 13],
      [8, 13],
      [13, 14],
      [10, 15],
      [15, 16],
      [11, 16],
      [16, 17],
      [12, 17],
      [17, 18],
      [13, 18],
      [18, 19]
    ],
    "coordinates": [
      [1, 1],
      [2, 1],
      [3, 1],
      [4, 1],
      [5, 1],
      [1, 2],
      [2, 2],
      [3, 2],
      [4, 2],
      [5, 2],
      [1, 3],
      [2, 3],
      [3, 3],
      [4, 3],
      [5, 3],
      [1, 4],
      [2, 4],
      [3, 4],
      [4, 4],
      [5, 4]
    ]
  },
  {
    "id": "likee",
    "name": "Likee",
    "version": "2024.04.1",
    "number_of_qubits": 8,
    "is_online": true,
    "last_online": null,
    "basis_gates": ["u", "h", "x"],
    "is_simulator": false,
    "coupling_map": [
      [0, 1],
      [1, 2],
      [0, 3],
      [1, 4],
      [3, 4],
      [2, 5],
      [4, 5],
      [3, 6],
      [5, 7],
      [6, 7]
    ],
    "coordinates": [
      [1, 1],
      [2, 1],
      [3, 2],
      [1, 2],
      [2, 2],
      [3, 2],
      [1, 3],
      [3, 3]
    ]
  },
  {
    "id": "thea",
    "name": "Thea",
    "version": "2023.06.0",
    "number_of_qubits": 5,
    "is_online": true,
    "last_online": null,
    "basis_gates": ["u", "h", "x"],
    "is_simulator": false,
    "coupling_map": [
      [0, 1],
      [0, 2],
      [2, 3],
      [1, 4],
      [3, 4]
    ],
    "coordinates": [
      [1, 1],
      [3, 1],
      [1, 2],
      [2, 2],
      [3, 2]
    ]
  }
]
